"""Domain models for the portfolio copilot."""

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime


@dataclass
class AlertEvent:
    """Represents a portfolio alert generated by the rule engine."""

    message: str
    timestamp: datetime
    severity: str
    rule_id: str
